-- =============================================================================
-- ACTUALIZAR ESQUEMA SIN PERDER DATOS
-- Base: defaultdb (Aiven)
--
-- SEGURO para ejecutar si YA tienes datos (Usuario, CERTIFICACION, etc.):
--   - Solo usa CREATE TABLE IF NOT EXISTS
--   - NO hace DROP, TRUNCATE ni DELETE
--   - NO inserta ni modifica filas existentes
--
-- DBeaver: Ctrl+A -> Ctrl+Alt+X (Execute SQL Script)
-- =============================================================================

USE defaultdb;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `android_metadata` (
  `locale` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `room_master_table` (
  `id` int NOT NULL,
  `identity_hash` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GENERO` (
  `IDPGENERO` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCIONGENERO` text NOT NULL,
  PRIMARY KEY (`IDPGENERO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TIPODOCUMENTO` (
  `IDTIPODOCUMENTO` int NOT NULL AUTO_INCREMENT,
  `NOMBREDOCUMENTO` text NOT NULL,
  PRIMARY KEY (`IDTIPODOCUMENTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ESTADOPOSTULACION` (
  `IDESTADOPOSTULACION` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCIONESTADOPOSTULACION` text NOT NULL,
  PRIMARY KEY (`IDESTADOPOSTULACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CATEGORIAHABILIDAD` (
  `IDCATEGORIAHABILIDAD` int NOT NULL AUTO_INCREMENT,
  `NOMBRECATEGORIAHABILIDAD` text NOT NULL,
  PRIMARY KEY (`IDCATEGORIAHABILIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `HABILIDAD` (
  `IDHABILIDAD` int NOT NULL AUTO_INCREMENT,
  `IDCATEGORIAHABILIDAD` int NOT NULL,
  `NOMBREHABILIDAD` text NOT NULL,
  PRIMARY KEY (`IDHABILIDAD`),
  KEY `index_HABILIDAD_CATEGORIA` (`IDCATEGORIAHABILIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` int NOT NULL AUTO_INCREMENT,
  `idEmpresa` int DEFAULT NULL,
  `idPostulante` int DEFAULT NULL,
  `nomUsuario` varchar(255) NOT NULL,
  `clave` varchar(255) NOT NULL,
  `rol` varchar(50) NOT NULL,
  PRIMARY KEY (`idUsuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `EMPRESA` (
  `IDEMPRESA` int NOT NULL AUTO_INCREMENT,
  `IDUSUARIO` int NOT NULL,
  `NOMBREEMPRESA` varchar(255) NOT NULL,
  `RAZONSOCIAL` varchar(255) NOT NULL,
  `CORREOEMPRESA` varchar(255) NOT NULL,
  `TELEFONOEMPRESA` varchar(50) NOT NULL,
  PRIMARY KEY (`IDEMPRESA`),
  UNIQUE KEY `index_EMPRESA_IDUSUARIO` (`IDUSUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `POSTULANTE` (
  `IDPOSTULANTE` int NOT NULL AUTO_INCREMENT,
  `IDGENERO` int NOT NULL,
  `IDTIPODOCUMENTO` int NOT NULL,
  `IDUSUARIO2` int NOT NULL,
  `NOMBREPOSTULANTE` varchar(255) NOT NULL,
  `APELLIDOPOSTULANTE` varchar(255) NOT NULL,
  `FECHANAC` varchar(50) NOT NULL,
  `DUI` varchar(50) NOT NULL,
  `NIT` varchar(50) NOT NULL,
  `DIRECCION` text NOT NULL,
  `CORREO` varchar(255) NOT NULL,
  PRIMARY KEY (`IDPOSTULANTE`),
  KEY `index_POSTULANTE_GENERO` (`IDGENERO`),
  KEY `index_POSTULANTE_TIPODOC` (`IDTIPODOCUMENTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `OfertaTrabajo` (
  `idOfertaTrabajo` int NOT NULL AUTO_INCREMENT,
  `idEmpresa` int NOT NULL,
  `tituloEducacion` text NOT NULL,
  `descripcionOferta` text NOT NULL,
  `salario` double NOT NULL,
  `fechaPublicacion` varchar(50) NOT NULL,
  PRIMARY KEY (`idOfertaTrabajo`),
  KEY `index_OfertaTrabajo_EMPRESA` (`idEmpresa`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `OFERTAHABILIDAD` (
  `IDOFERTAHABILIDAD` int NOT NULL AUTO_INCREMENT,
  `IDHABILIDAD` int NOT NULL,
  `IDOFERTATRABAJO` int NOT NULL,
  `NIVEL` varchar(50) NOT NULL,
  PRIMARY KEY (`IDOFERTAHABILIDAD`),
  KEY `index_OFERTAHABILIDAD_HABILIDAD` (`IDHABILIDAD`),
  KEY `index_OFERTAHABILIDAD_OFERTA` (`IDOFERTATRABAJO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `POSTULACION` (
  `IDPOSTULACION` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `IDOFERTATRABAJO` int NOT NULL,
  `FECHAPOSTULACION` varchar(50) NOT NULL,
  `IDESTADOPOSTULACION` int NOT NULL,
  PRIMARY KEY (`IDPOSTULACION`),
  KEY `index_POSTULACION_POSTULANTE` (`IDPOSTULANTE`),
  KEY `index_POSTULACION_OFERTA` (`IDOFERTATRABAJO`),
  KEY `index_POSTULACION_ESTADO` (`IDESTADOPOSTULACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `EDUCACION` (
  `idEducacion` int NOT NULL AUTO_INCREMENT,
  `idPostulante` int NOT NULL,
  `idNivelAcademico` int NOT NULL,
  `tituloEducacion` text NOT NULL,
  `institucion` text NOT NULL,
  `fechaInicio` varchar(50) NOT NULL,
  `fechaFin` varchar(50) NOT NULL,
  `estadoCurso` int NOT NULL,
  PRIMARY KEY (`idEducacion`),
  KEY `index_EDUCACION_POSTULANTE` (`idPostulante`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `NIVELACADEMICO` (
  `IDNIVELACADEMICO` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `IDEDUCACION` int NOT NULL,
  `NOMBREDOCUMENTO` text NOT NULL,
  PRIMARY KEY (`IDNIVELACADEMICO`),
  KEY `index_NIVELACADEMICO_POSTULANTE` (`IDPOSTULANTE`),
  KEY `index_NIVELACADEMICO_EDUCACION` (`IDEDUCACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `EXPERIENCIALABORAL` (
  `IDEXPERIENCIALABORAL` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `PUESTO` text NOT NULL,
  `FECHAINICIO` varchar(50) NOT NULL,
  `FECHAFIN` varchar(50) DEFAULT NULL,
  `FUNCIONES` text NOT NULL,
  `NOMBREEMPRESA` text NOT NULL,
  `CONTACTOEMPRESA` text NOT NULL,
  PRIMARY KEY (`IDEXPERIENCIALABORAL`),
  KEY `index_EXPERIENCIALABORAL_IDPOSTULANTE` (`IDPOSTULANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CERTIFICACION` (
  `IDCERTIFICACION` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `NOMBRECERTIFICACION` text NOT NULL,
  `TIPOCERTIFICACION` text NOT NULL,
  `CODIGOCERTIFICACION` text NOT NULL,
  `INSTITUCIONCERTIFICACION` text NOT NULL,
  `FECHACERTIFICACION` varchar(50) NOT NULL,
  PRIMARY KEY (`IDCERTIFICACION`),
  KEY `index_CERTIFICACION_IDPOSTULANTE` (`IDPOSTULANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `IDIOMA` (
  `IDIDIOMA` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `NOMBREIDIOMA` text NOT NULL,
  `NIVELIDIOMA` text NOT NULL,
  PRIMARY KEY (`IDIDIOMA`),
  KEY `index_IDIOMA_IDPOSTULANTE` (`IDPOSTULANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CARTA` (
  `IDCARTA` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `TITULOCARTA` text NOT NULL,
  `CONTENIDOCARTA` text NOT NULL,
  PRIMARY KEY (`IDCARTA`),
  KEY `index_CARTA_IDPOSTULANTE` (`IDPOSTULANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `REFERENCIA` (
  `IDREFERENCIA` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `NOMBREFERENCIA` text NOT NULL,
  `PARENTESCO` text NOT NULL,
  `TELEFONO` varchar(50) NOT NULL,
  PRIMARY KEY (`IDREFERENCIA`),
  KEY `index_REFERENCIA_IDPOSTULANTE` (`IDPOSTULANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PHONE` (
  `IDTELEFONO` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `NUMEROTELEFONO` varchar(50) NOT NULL,
  `TIPOTELEFONO` varchar(50) NOT NULL,
  PRIMARY KEY (`IDTELEFONO`),
  KEY `index_PHONE_IDPOSTULANTE` (`IDPOSTULANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `REDSOCIAL` (
  `idRed` int NOT NULL AUTO_INCREMENT,
  `idPostulante` int NOT NULL,
  `nombreRed` varchar(100) NOT NULL,
  `enlace` text NOT NULL,
  PRIMARY KEY (`idRed`),
  KEY `index_REDSOCIAL_POSTULANTE` (`idPostulante`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;

-- Verifica que tus datos siguen intactos
SELECT 'Usuario' AS tabla, COUNT(*) AS registros FROM Usuario
UNION ALL SELECT 'POSTULANTE', COUNT(*) FROM POSTULANTE
UNION ALL SELECT 'CERTIFICACION', COUNT(*) FROM CERTIFICACION;

SELECT table_name AS tabla
FROM information_schema.tables
WHERE table_schema = 'defaultdb'
  AND table_type = 'BASE TABLE'
ORDER BY table_name;
