-- Importar en Aiven -> defaultdb (DBeaver: ejecutar todo el script)
-- Compatible con MySQL 8.x (sin cabeceras phpMyAdmin)

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `android_metadata` (
  `locale` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CARTA` (
  `IDCARTA` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `TITULOCARTA` text NOT NULL,
  `CONTENIDOCARTA` text NOT NULL,
  PRIMARY KEY (`IDCARTA`),
  KEY `index_CARTA_IDPOSTULANTE` (`IDPOSTULANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CATEGORIAHABILIDAD` (
  `IDCATEGORIAHABILIDAD` int NOT NULL AUTO_INCREMENT,
  `NOMBRECATEGORIAHABILIDAD` text NOT NULL,
  PRIMARY KEY (`IDCATEGORIAHABILIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `CERTIFICACION` (
  `IDCERTIFICACION` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `NOMBRECERTIFICACION` text NOT NULL,
  `TIPOCERTIFICACION` text NOT NULL,
  `CODIGOCERTIFICACION` text NOT NULL,
  `INSTITUCIONCERTIFICACION` text NOT NULL,
  `FECHACERTIFICACION` varchar(50) NOT NULL,
  PRIMARY KEY (`IDCERTIFICACION`),
  KEY `index_CERTIFICACION_IDPOSTULANTE` (`IDPOSTULANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `EDUCACION` (
  `idEducacion` int NOT NULL AUTO_INCREMENT,
  `idPostulante` int NOT NULL,
  `idNivelAcademico` int NOT NULL,
  `tituloEducacion` text NOT NULL,
  `institucion` text NOT NULL,
  `fechaInicio` varchar(50) NOT NULL,
  `fechaFin` varchar(50) NOT NULL,
  `estadoCurso` int NOT NULL,
  PRIMARY KEY (`idEducacion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `EMPRESA` (
  `IDEMPRESA` int NOT NULL AUTO_INCREMENT,
  `IDUSUARIO` int NOT NULL,
  `NOMBREEMPRESA` varchar(255) NOT NULL,
  `RAZONSOCIAL` varchar(255) NOT NULL,
  `CORREOEMPRESA` varchar(255) NOT NULL,
  `TELEFONOEMPRESA` varchar(50) NOT NULL,
  PRIMARY KEY (`IDEMPRESA`),
  UNIQUE KEY `index_EMPRESA_IDUSUARIO` (`IDUSUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `ESTADOPOSTULACION` (
  `IDESTADOPOSTULACION` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCIONESTADOPOSTULACION` text NOT NULL,
  PRIMARY KEY (`IDESTADOPOSTULACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `EXPERIENCIALABORAL` (
  `IDEXPERIENCIALABORAL` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `PUESTO` text NOT NULL,
  `FECHAINICIO` varchar(50) NOT NULL,
  `FECHAFIN` varchar(50) DEFAULT NULL,
  `FUNCIONES` text NOT NULL,
  `NOMBREEMPRESA` text NOT NULL,
  `CONTACTOEMPRESA` text NOT NULL,
  PRIMARY KEY (`IDEXPERIENCIALABORAL`),
  KEY `index_EXPERIENCIALABORAL_IDPOSTULANTE` (`IDPOSTULANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GENERO` (
  `IDPGENERO` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCIONGENERO` text NOT NULL,
  PRIMARY KEY (`IDPGENERO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `HABILIDAD` (
  `IDHABILIDAD` int NOT NULL AUTO_INCREMENT,
  `IDCATEGORIAHABILIDAD` int NOT NULL,
  `NOMBREHABILIDAD` text NOT NULL,
  PRIMARY KEY (`IDHABILIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `IDIOMA` (
  `IDIDIOMA` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `NOMBREIDIOMA` text NOT NULL,
  `NIVELIDIOMA` text NOT NULL,
  PRIMARY KEY (`IDIDIOMA`),
  KEY `index_IDIOMA_IDPOSTULANTE` (`IDPOSTULANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `NIVELACADEMICO` (
  `IDNIVELACADEMICO` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `IDEDUCACION` int NOT NULL,
  `NOMBREDOCUMENTO` text NOT NULL,
  PRIMARY KEY (`IDNIVELACADEMICO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `OFERTAHABILIDAD` (
  `IDOFERTAHABILIDAD` int NOT NULL AUTO_INCREMENT,
  `IDHABILIDAD` int NOT NULL,
  `IDOFERTATRABAJO` int NOT NULL,
  `NIVEL` varchar(50) NOT NULL,
  PRIMARY KEY (`IDOFERTAHABILIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `OfertaTrabajo` (
  `idOfertaTrabajo` int NOT NULL AUTO_INCREMENT,
  `idEmpresa` int NOT NULL,
  `tituloEducacion` text NOT NULL,
  `descripcionOferta` text NOT NULL,
  `salario` double NOT NULL,
  `fechaPublicacion` varchar(50) NOT NULL,
  PRIMARY KEY (`idOfertaTrabajo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PHONE` (
  `IDTELEFONO` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `NUMEROTELEFONO` varchar(50) NOT NULL,
  `TIPOTELEFONO` varchar(50) NOT NULL,
  PRIMARY KEY (`IDTELEFONO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `POSTULACION` (
  `IDPOSTULACION` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `IDOFERTATRABAJO` int NOT NULL,
  `FECHAPOSTULACION` varchar(50) NOT NULL,
  `IDESTADOPOSTULACION` int NOT NULL,
  PRIMARY KEY (`IDPOSTULACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `POSTULANTE` (
  `IDPOSTULANTE` int NOT NULL AUTO_INCREMENT,
  `IDGENERO` int NOT NULL,
  `IDTIPODOCUMENTO` int NOT NULL,
  `IDUSUARIO2` int NOT NULL,
  `NOMBREPOSTULANTE` varchar(255) NOT NULL,
  `APELLIDOPOSTULANTE` varchar(255) NOT NULL,
  `FECHANAC` varchar(50) NOT NULL,
  `DUI` varchar(50) NOT NULL,
  `NIT` varchar(50) NOT NULL,
  `DIRECCION` text NOT NULL,
  `CORREO` varchar(255) NOT NULL,
  PRIMARY KEY (`IDPOSTULANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `REDSOCIAL` (
  `idRed` int NOT NULL AUTO_INCREMENT,
  `idPostulante` int NOT NULL,
  `nombreRed` varchar(100) NOT NULL,
  `enlace` text NOT NULL,
  PRIMARY KEY (`idRed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `REFERENCIA` (
  `IDREFERENCIA` int NOT NULL AUTO_INCREMENT,
  `IDPOSTULANTE` int NOT NULL,
  `NOMBREFERENCIA` text NOT NULL,
  `PARENTESCO` text NOT NULL,
  `TELEFONO` varchar(50) NOT NULL,
  PRIMARY KEY (`IDREFERENCIA`),
  KEY `index_REFERENCIA_IDPOSTULANTE` (`IDPOSTULANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `room_master_table` (
  `id` int NOT NULL,
  `identity_hash` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `TIPODOCUMENTO` (
  `IDTIPODOCUMENTO` int NOT NULL AUTO_INCREMENT,
  `NOMBREDOCUMENTO` text NOT NULL,
  PRIMARY KEY (`IDTIPODOCUMENTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` int NOT NULL AUTO_INCREMENT,
  `idEmpresa` int DEFAULT NULL,
  `idPostulante` int DEFAULT NULL,
  `nomUsuario` varchar(255) NOT NULL,
  `clave` varchar(255) NOT NULL,
  `rol` varchar(50) NOT NULL,
  PRIMARY KEY (`idUsuario`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `android_metadata` (`locale`) VALUES ('es_US');

INSERT INTO `GENERO` (`IDPGENERO`, `DESCRIPCIONGENERO`) VALUES
(1, 'Femenino'),
(2, 'Masculino');

INSERT INTO `TIPODOCUMENTO` (`IDTIPODOCUMENTO`, `NOMBREDOCUMENTO`) VALUES
(1, 'DUI'),
(2, 'Pasaporte');

INSERT INTO `POSTULANTE` (
  `IDPOSTULANTE`, `IDGENERO`, `IDTIPODOCUMENTO`, `IDUSUARIO2`,
  `NOMBREPOSTULANTE`, `APELLIDOPOSTULANTE`, `FECHANAC`, `DUI`, `NIT`, `DIRECCION`, `CORREO`
) VALUES (
  1, 2, 1, 1,
  'David', 'Lemus', '2004-01-01', '12345678-9', '0614-123456-101-1', 'Apopa', 'david@gmail.com'
);

INSERT INTO `EMPRESA` (`IDEMPRESA`, `IDUSUARIO`, `NOMBREEMPRESA`, `RAZONSOCIAL`, `CORREOEMPRESA`, `TELEFONOEMPRESA`) VALUES
(1, 1, '', '', '', ''),
(2, 2, 'fff', 'bwjwkk', 'ssd@ka.com', '7282929');

INSERT INTO `Usuario` (`idUsuario`, `idEmpresa`, `idPostulante`, `nomUsuario`, `clave`, `rol`) VALUES
(1, NULL, 1, '', '1', 'Postulante');

INSERT INTO `room_master_table` (`id`, `identity_hash`) VALUES
(42, 'c337ff42925b9435dbfdf6cfaf896c28');

SET FOREIGN_KEY_CHECKS = 1;
