-- Script inicial para MySQL (importar con DBeaver, phpMyAdmin o consola mysql)
-- Base de datos: bolsatrabajo (o el nombre que definas en DB_NAME)

CREATE TABLE IF NOT EXISTS `android_metadata` (
    `locale` TEXT
);

CREATE TABLE IF NOT EXISTS `GENERO` (
    `IDPGENERO` INT NOT NULL AUTO_INCREMENT,
    `DESCRIPCIONGENERO` TEXT NOT NULL,
    PRIMARY KEY (`IDPGENERO`)
);

CREATE TABLE IF NOT EXISTS `TIPODOCUMENTO` (
    `IDTIPODOCUMENTO` INT NOT NULL AUTO_INCREMENT,
    `NOMBREDOCUMENTO` TEXT NOT NULL,
    PRIMARY KEY (`IDTIPODOCUMENTO`)
);

CREATE TABLE IF NOT EXISTS `POSTULANTE` (
    `IDPOSTULANTE` INT NOT NULL AUTO_INCREMENT,
    `IDGENERO` INT NOT NULL,
    `IDTIPODOCUMENTO` INT NOT NULL,
    `IDUSUARIO2` INT NOT NULL,
    `NOMBREPOSTULANTE` VARCHAR(255) NOT NULL,
    `APELLIDOPOSTULANTE` VARCHAR(255) NOT NULL,
    `FECHANAC` VARCHAR(50) NOT NULL,
    `DUI` VARCHAR(50) NOT NULL,
    `NIT` VARCHAR(50) NOT NULL,
    `DIRECCION` TEXT NOT NULL,
    `CORREO` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`IDPOSTULANTE`)
);

CREATE TABLE IF NOT EXISTS `Usuario` (
    `idUsuario` INT NOT NULL AUTO_INCREMENT,
    `idEmpresa` INT,
    `idPostulante` INT,
    `nomUsuario` VARCHAR(255) NOT NULL,
    `clave` VARCHAR(255) NOT NULL,
    `rol` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`idUsuario`)
);

CREATE TABLE IF NOT EXISTS `CERTIFICACION` (
    `IDCERTIFICACION` INT NOT NULL AUTO_INCREMENT,
    `IDPOSTULANTE` INT NOT NULL,
    `NOMBRECERTIFICACION` TEXT NOT NULL,
    `TIPOCERTIFICACION` TEXT NOT NULL,
    `CODIGOCERTIFICACION` TEXT NOT NULL,
    `INSTITUCIONCERTIFICACION` TEXT NOT NULL,
    `FECHACERTIFICACION` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`IDCERTIFICACION`),
    CONSTRAINT `fk_cert_postulante` FOREIGN KEY (`IDPOSTULANTE`) REFERENCES `POSTULANTE` (`IDPOSTULANTE`)
);

INSERT INTO `android_metadata` (`locale`) VALUES ('es_US')
ON DUPLICATE KEY UPDATE `locale` = VALUES(`locale`);

INSERT INTO `GENERO` (`IDPGENERO`, `DESCRIPCIONGENERO`) VALUES (1, 'Femenino')
ON DUPLICATE KEY UPDATE `DESCRIPCIONGENERO` = VALUES(`DESCRIPCIONGENERO`);

INSERT INTO `TIPODOCUMENTO` (`IDTIPODOCUMENTO`, `NOMBREDOCUMENTO`) VALUES (1, 'DUI')
ON DUPLICATE KEY UPDATE `NOMBREDOCUMENTO` = VALUES(`NOMBREDOCUMENTO`);

INSERT INTO `POSTULANTE` (
    `IDPOSTULANTE`, `IDGENERO`, `IDTIPODOCUMENTO`, `IDUSUARIO2`,
    `NOMBREPOSTULANTE`, `APELLIDOPOSTULANTE`, `FECHANAC`, `DUI`, `NIT`, `DIRECCION`, `CORREO`
) VALUES (
    1, 1, 1, 4,
    'Postulante', 'Prueba', '01/01/2000', '00000000-0', '0000000-0', 'San Salvador', 'pos@test.com'
)
ON DUPLICATE KEY UPDATE `NOMBREPOSTULANTE` = VALUES(`NOMBREPOSTULANTE`);

INSERT INTO `Usuario` (`idUsuario`, `idEmpresa`, `idPostulante`, `nomUsuario`, `clave`, `rol`) VALUES
(4, NULL, 1, 'pos', '1', 'Postulante')
ON DUPLICATE KEY UPDATE `idPostulante` = VALUES(`idPostulante`);

CREATE INDEX `index_CERTIFICACION_IDPOSTULANTE` ON `CERTIFICACION` (`IDPOSTULANTE`);
